Recursive validation
SpineEventEngine/dart pull request #12
Opened 2020-09-29 09:12 UTC by dmdashenkov

2020-09-30 10:26 UTC, dmdashenkov commented
@armiol, PTAL.

2020-09-30 11:22 UTC, armiol requested changes
@dmdashenkov please see my comments. I am not able to tell I understand the idea completely. But it's better than I thought it would be — given my lack of Dart experience :)

Please consider putting more details into the PR description telling of the under-the-hood actions. For instance, you could tell a small story and incorporate that compilation restriction we have, etc.

2020-09-30 11:22 UTC, armiol commented on codegen/lib/src/constraint_violation.dart
> +        var childConstrainsParam = Parameter((b) => b
`constraints`?

2020-09-30 11:22 UTC, armiol commented on codegen/lib/src/field_validator_factory.dart
> +/// A function of a field value expresion to code which prepares context before the constraint
Please move the phrase starting with `before` to the next line. This won't leave a "check" alone in the dark.

2020-09-30 11:22 UTC, armiol commented on codegen/lib/src/field_validator_factory.dart
> +/// A function of a field value expresion to code which prepares context before the constraint
`expression`?

And honestly, I don't understand.
Can you please explain in more detail and maybe have an example?

2020-09-30 12:19 UTC, alexander-yevsyukov commented on client/src/test/proto/spine/test/tools/dart/validation.proto
> +    repeated TaskId backlog = 3 [(validate) = true];
Please document this field. Its purpose isn't quite clear.

2020-10-01 11:43 UTC, dmdashenkov commented
@armiol, PTAL.

2020-10-01 14:29 UTC, armiol approved these changes
@dmdashenkov LGTM

2020-10-01 14:41 UTC, alexander-yevsyukov approved these changes
LGTM

2020-10-01 14:47 UTC, merged