Prototype `build-tasks.gradle` and `pub-publish-tasks.gradle` in Kotlin
SpineEventEngine/dart pull request #36
Opened 2021-11-08 17:28 UTC by yevhenii-nadtochii

This is not going to be merged as approved. A separate PR into config repository would be created.

2021-11-09 19:13 UTC, armiol requested changes
@yevhenii-nadtochii LGTM in general. Please see my comments. 

I'd like to review this draft one more time once the comments are addressed.

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/Dart.kt
> + * Encapsulates Dart related configuration.
Let's not use this "encapsulates" at all. It tells nothing. I would start like this: 

``` 
Gradle extension which ...
```

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/Dart.kt
> + * Defines the scope for Dart related configuration.
It's "Dart-related". Here and in other documentation pieces.

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/Build.kt
> + * dart {
Do we need users to import anything? If so, please specify.

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/Publish.kt
> +            logger.debug("Prepared Pub publication in directory `$publicationDirectory`.")
```
Pub publication is prepared in the directory `...`.
```

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/Publish.kt
> +            exclude("proto/", "generated/", "build/", "**/.*")
I would document this somewhere. It seems important.

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/task/Publish.kt
> +private fun DartTasks.activateLocally(): Task =
Please document this one. It's not very obvious. I would expect a link to the description of local activation — if that's a thing.

2021-11-09 19:13 UTC, armiol commented on client/build.gradle.kts
> +        registerBuildTasks()
Can we turn it into this?
```
register(build(), publish())
```
It's two "register" (and I want to have just one), and two redundant "Tasks" (which is the context in which we operate already) to kill.

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/Dart.kt
> +    val dartBuildTask = "Dart/Build"
I would consider reducing the visibility of the constants to `internal`.

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/Dart.kt
> +    @Suppress("LeakingThis")
Please comment on suppressions like this one.

2021-11-09 19:13 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/gradle/dart/Dart.kt
> +interface DartEnvironment {
We need an example on how to customize it.

2021-12-10 12:08 UTC, yevhenii-nadtochii commented
Closing this draft as an associated PR into `config` repository is created.
See [Migrate `buildSrc/.../groovy/dart/*` scripts to Kotlin ](https://github.com/SpineEventEngine/config/pull/311)

2021-12-10 12:08 UTC, closed without merging