Implement subscriptions
SpineEventEngine/dart pull request #6
Opened 2019-11-20 21:01 UTC by dmitrykuzmin

This PR adds entity/event subscriptions to the Dart client.

The subscriptions are exposed through the `BackendClient.subscribeTo(Topic)` method which returns a holder of `itemAdded`, `itemChanged` and `itemDeleted` streams.

Example is as follows:
```dart
Topic topic = requests.topic().all(TaskListView());
Subscription<TaskListView> subscription = await client.subscribeTo(topic);
subscription.itemChanged.listen(taskListView => updateDisplay(taskListView));
```

The exposed streams propagate all the changes which happen to entities/events and are broadcast, i.e. can be listened to by multiple callers simultaneously.

The subscription is cancelled with the `Subscription.unsubscribe()` method. This causes the server to cancel the subscription and stop reflecting the changes into the Firebase.

--------------

REST Firebase client, for now, does not support the subscriptions.

The integration tests were thus migrated to using the Firebase App based client which works only in web environment. 

As a consequence, the integration tests are now run in the browser, locally and on CI.

2019-11-20 21:03 UTC, dmitrykuzmin commented
@armiol, @dmdashenkov PTAL.

2019-11-21 11:37 UTC, dmdashenkov requested changes

2019-11-21 11:37 UTC, dmdashenkov commented on client/lib/backend_client.dart
> +    static final Duration subscriptionKeepUpPeriod = new Duration(minutes: 2);
Please make this attribute configurable with a default value.

2019-11-21 11:37 UTC, dmdashenkov commented on client/lib/firebase_client.dart
> +    Stream<String> childAdded(String path);
Please add doc on the node values. You could reference the doc of `get(..)`.

2019-11-21 11:37 UTC, dmdashenkov commented on integration-tests/client-test/integration-test/client_test.dart
> +            ..name = 'New task name';
Please fix the alignment.

2019-11-21 12:46 UTC, dmitrykuzmin commented
@dmdashenkov PTAL again.

2019-11-21 13:09 UTC, dmdashenkov requested changes

2019-11-21 13:09 UTC, dmdashenkov commented on client/lib/backend_client.dart
> +    Duration subscriptionKeepUpPeriod = new Duration(minutes: 2);
Please make it `final` and add a constructor param. Most likely, the  `Duration` ctor is not `const`, thus you'll have to initialize the field manually.

2019-11-21 13:09 UTC, dmdashenkov commented on client/lib/backend_client.dart
> +    Duration subscriptionKeepUpPeriod = new Duration(minutes: 2);
The `new` keyword is optional in Dart. Let's not use it.

2019-11-21 13:09 UTC, dmdashenkov commented on client/lib/spine_client.dart
> +///     subscription.itemChanged.listen(taskListView => updateDisplay(taskListView));
Please place this above the querying. It's a common pattern to subscribe to updates and then query the current state. This way we do not lose any data.

2019-11-21 13:09 UTC, dmdashenkov commented on client/lib/subscription.dart
> +                'All streams passed to an EntitySubscription instance should be broadcast.');
```suggestion
                'All streams passed to an `EntitySubscription` instance should be broadcast.');
```

2019-11-21 13:09 UTC, dmdashenkov commented on client/lib/subscription.dart
> +    static Stream<T> checkIsBroadCast<T>(Stream<T> stream) {
```suggestion
    static Stream<T> _checkIsBroadCast<T>(Stream<T> stream) {
```

2019-11-21 13:52 UTC, dmitrykuzmin commented
@dmdashenkov PTAL again.

2019-11-21 13:58 UTC, dmdashenkov approved these changes

2019-11-22 16:54 UTC, armiol requested changes
@dmitrykuzmin LGTM in general. Please see my comments.

2019-11-22 16:54 UTC, armiol commented on client/lib/subscription.dart
> +/// The streams are broadcast, i.e. can be listened to more than once, and receive all the state
Can you please rephrase. I am not sure I understand the English here.

2019-11-22 16:54 UTC, armiol commented on integration-tests/client-test/build.gradle
> +    commandLine pub, 'run', 'test', integrationTestDir, '-p', 'chrome'
Please have a comment on the flag.

2019-11-23 14:47 UTC, dmitrykuzmin commented
@armiol PTAL again.

2019-11-26 15:24 UTC, armiol approved these changes

2019-11-26 16:05 UTC, merged